//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academia.Models.db
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Docente
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<double> Salario { get; set; }
        public Nullable<bool> eshombre { get; set; }
        public Nullable<int> id_dedicacion { get; set; }
        public string especialidad { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fechanacimiento { get; set; }
        public Nullable<int> id_tipoSangre { get; set; }
    
        public virtual Dedicacion Dedicacion { get; set; }
        public virtual TipoSangre TipoSangre { get; set; }
    }
}
