//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academia.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        public int id { get; set; }
        public Nullable<int> id_Asignatura { get; set; }
        public Nullable<int> id_Estudiante { get; set; }
        public string actividad { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> porcentaje { get; set; }
        public Nullable<double> nota1 { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual Estudiante Estudiante { get; set; }
    }
}
